version: "3"

services:
  db:
    image: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - infra
  
  pgmyadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 80:80
    networks:
      - infra
  
  sftp:
    image: atmoz/sftp
    volumes:
        - ./sftp-upload:/home/simuladorsftp/upload
    ports:
        - "22:22"
    command: simuladorsftp:pass
    networks:
      - infra

networks:
  infra:
    driver: bridge